#!/bin/sh
set -e
#DEBHELPER#
echo ""
echo "picam-recorder installed."
echo "  recorder config : /etc/picam-recorder/recorder.ini"
echo "  systemd service : /lib/systemd/system/picam-recorder.service"
echo ""
echo "  Edit config then: systemctl enable --now picam-recorder"
