#!/bin/sh
set -e
if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    rm -f /usr/local/bin/picam-recorder
fi
if [ "$1" = "purge" ]; then
    rm -rf /etc/picam-recorder
    rm -rf /var/lib/picam-recorder
fi
